#!/usr/bin/env bash
set -ex

project_dir=$(pwd)

prefix="$project_dir/out/usr"
test_build=false
while [ $# -gt 0 ]; do
  case "$1" in
    --prefix)
      prefix=$2
      shift
      ;;
    --test)
      test_build=true
      ;;
    -h|--help)
      printf "$help"
      exit
      ;;
    --*)
      echo "Illegal option $1"
      ;;
  esac
  shift $(( $# > 0 ? 1 : 0 ))
done

script/node-headers

cd ${project_dir}/deps/mutils
build_dir="$project_dir/out/build/mutils"
./config \
  --build-dir="$build_dir" \
  --build-library-type="STATIC" \
  --cmake-modules="$project_dir/deps/cmake-modules" \
  --prefix="$prefix"
cd $build_dir
make
make install

cd ${project_dir}/deps/flora
build_dir="$project_dir/out/build/flora"

./config \
  --build-dir="$build_dir" \
  --build-library-type="STATIC" \
  --cli-log-level="error" \
  --cmake-modules="$project_dir/deps/cmake-modules" \
  --find_root_path="$prjroot/out" \
  --prefix="$prefix"
cd $build_dir
make
make install

cd $project_dir
build_dir="$project_dir/out/build/node-flora"

./config \
  --build-dir="$build_dir" \
  --cmake-modules="$project_dir/deps/cmake-modules" \
  --find_root_path="$prjroot/out" \
  --prefix="$prefix" \
  --napi=$(node -e "console.log(require('path').dirname(require.resolve('node-addon-api')))") \
  --search-node-headers
cd $build_dir
make
cp $build_dir/flora-cli.node $project_dir

cd $project_dir
